# Guia de Introdução ao NumPy

NumPy, que significa Numerical Python, é uma biblioteca fundamental para a computação científica em Python. Ela fornece suporte para arrays e matrizes, além de funções matemáticas para operações com esses objetos. É, também, a base da biblioteca Pandas.



## Instalação

Para instalar o NumPy, você pode usar o pip, que é o gerenciador de pacotes do Python.

```python
pip install numpy
```

## Arrays

Um array é uma estrutura de dados que armazena valores do mesmo tipo. Em Python, isso é uma grande vantagem porque economiza espaço e permite operações mais eficientes. Vamos criar um array.



In [1]:
import numpy as np

# Criação de um array
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [ ]:
print(array[0])

# Para pegar o último item de um array, printar print(array[-1])

In [3]:
# Slicing: pegar apenas trechos de um array
print(array[1:4])

[2 3 4]


In [4]:
# No slicing, o último item do array não é incluído
print(array[0:-1])

[1 2 3 4]


In [5]:
# O último número é o step, ou seja, vai do primeiro ao último item (sem contar este), de 2 em 2
print(array[0:-1:2])

[1 3]


In [6]:
# Neste exemplo, ele não botou qual é o número que ele deseja parar, então foi do primeiro ao último (incluindo o último, que no caso é o número 5) de 2 em 2

print(array[0::2])

[1 3 5]


In [7]:
# Se quisermos pegar do primeiro ao último (incluindo o último), de 2 em 2, não precisamos indicar isso, apenas o passo 
print(array[::2])

[1 3 5]


In [8]:
# Todo o array é impresso
print(array[::])

[1 2 3 4 5]


In [9]:
# No caso abaixo, todo o array é impresso, mas ao contrário
print(array[::-1])

[5 4 3 2 1]
